return {
	-- Themes are managed by theme.lua (aether) + all-themes.lua (library)
	-- This file is kept for reference. Enable any alternative theme below.

	-- Kanagawa Dragon (HatDots classic)
	-- {
	-- 	"rebelot/kanagawa.nvim",
	-- 	lazy = true,
	-- 	opts = {
	-- 		theme = "dragon",
	-- 		transparent = true,
	-- 		overrides = function(colors)
	-- 			local palette = colors.palette
	-- 			local theme = colors.theme
	-- 			return {
	-- 				Normal = { bg = "none" },
	-- 				NormalNC = { bg = "none" },
	-- 				NormalFloat = { bg = "none" },
	-- 				SignColumn = { bg = "none" },
	-- 				LineNr = { bg = "none" },
	-- 				FoldColumn = { bg = "none" },
	-- 				FloatBorder = { bg = "none", fg = theme.ui.float.fg_border },
	-- 				Pmenu = { bg = "none" },
	-- 				PmenuSel = { bg = palette.waveBlue1 },
	-- 				CursorLine = { bg = "none" },
	-- 				Visual = { bg = palette.waveBlue1 },
	-- 				TelescopeNormal = { bg = "none" },
	-- 				TelescopeBorder = { bg = "none", fg = theme.ui.float.fg_border },
	-- 			}
	-- 		end,
	-- 	},
	-- },

	-- Oxocarbon (HatDots previous default)
	-- {
	-- 	"nyoom-engineering/oxocarbon.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.opt.background = "dark"
	-- 		vim.cmd.colorscheme("oxocarbon")
	-- 	end,
	-- },
}
